### PR TITLE
Ets2 ats update139 update2020

### PR DESCRIPTION
**Pull request by meatlayer**

### CODE REVIEW

**Comment by ExploringAussie** [comment]
The 1.39 maps do not work for me, ats is stuck on Loading map, please wait, and I also tried using the promod map for ATS and the icon was not accurate of where I was in game, any ideas?

**Comment by meatlayer** [comment]
Try downloading the latest release from here - https://github.com/meatlayer/ets2-mobile-route-advisor/releases

After the release of the Iberia DLC, I hope to re-capture maps for all the games. Also, make sure that you have the ETS2 Telemetry Server running correctly and that the browser does not block anything with additional extensions.

**Comment by ExploringAussie** [comment]
> Try downloading the latest release from here - https://github.com/meatlayer/ets2-mobile-route-advisor/releases/tag/3.6.2
> 
> After the release of the Iberia DLC, I hope to re-capture maps for all the games. Also, make sure that you have the ETS2 Telemetry Server running correctly and that the browser does not block anything with additional extensions.

yea thats where I downloaded it from, server is running correctly, works if I use the promod map (though cords are off) but if I try to use the standard map just stuck on Loading map, please wait....

**Comment by ExploringAussie** [comment]
So I just tried on ets2, same thing, stuck on loading map, copied the promod map to a folder named ets2Mod, changed the config file to point to that map, works straight away, only issue is the cords are off as well as ive attached a pic to show you


image

**Comment by ExploringAussie** [comment]
Sorry to spam you, but bit of a update, realised im on 1.40, though that shouldnt of been a issue, but ive compared my ingame map to your map (ets2 promod + rus), and seems they have updated the map, this is just one example but looking through there is so much difference, so im not sure if this is apart of the 1.40 update or not? Left is in game and right is your map (promod + rus)
I'll wait for your 1.40 update and see if your map matches mine then, as all I have the promod and rus map installed.

Also one small request, are you able to make the icons larger? I noticed the standard map (non modded) has much larger icons.
Thanks again.
image


Edit: Can confirm its 1.40 the map has changed (even the standard map), I just downloaded 1.39 and the map is the same as yours.

**Comment by meatlayer** [comment]
I have updated to the latest version 1.40 in my map repository.

**Comment by ExploringAussie** [comment]
Yea its weird, sometimes the location of the arrow to the map is perfect, but othertimes its way off even the standard map. The flags are always in the correct locations though.

**Pull request closed without merging**
