### PR TITLE
Update max speed indicator

### LINKED ISSUE #185: Speedlimit signs
Great job for this game! Congratulations.
But I've a problem. I can't see numbers in speedlimit signs. Any suggestion?

I open the

### PR DESCRIPTION
**Pull request by wimulkeman**
Use the speed limit from the telemetry data to update the max speed indicator shown on the map tab.

Fixes #185

### CODE REVIEW

**Comment by WarLord211** [comment]
i testet it for myself and have the problem that in ATS (there i use Miles) the limit sign it then metric now.

**Comment by wimulkeman** [comment]
@WarLord211 Thanks for testing the update. I've added an additional fix to switch between kilometers and miles depending on the value in the config.

**Comment by WarLord211** [comment]
work for me now. 
Maybe think about to adopt it to [meatlayers](https://github.com/meatlayer/ets2-mobile-route-advisor) Version because this is maintained and not death as this version.
 Then you Cout make the PR at his version

**Comment by wimulkeman** [comment]
Thanks for the tip. I will move my PR to the suggested fork.

**Pull request closed without merging**
