### PR TITLE
Added Dutch Translation

### PR DESCRIPTION
**Pull request by TheHell34**

### CODE REVIEW

**Comment by mkoch227** [comment]
It looks like there are some missing strings in your language file (for example, the days of the week are missing), which is probably because the `en-US.json` template was not up-to-date :frowning: .  Can you look at the updated `en-US.json` file and update your translation accordingly?

**Comment by TheHell34** [comment]
Sure

**Comment by TheHell34** [comment]
Done

**Comment by mkoch227** [comment]
looks good, thanks!

**Pull request merged**
